package com.fmps.autotrader.core.traders

import com.fmps.autotrader.shared.dto.InstantSerializer
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable
import java.time.Instant

/**
 * Represents a trading signal generated by a strategy.
 *
 * A trading signal contains the recommended action (BUY, SELL, HOLD, CLOSE),
 * confidence level, reasoning, and supporting indicator values.
 *
 * @property action The recommended trading action
 * @property confidence Confidence level from 0.0 (low) to 1.0 (high)
 * @property reason Human-readable explanation of why this signal was generated
 * @property timestamp When the signal was generated
 * @property indicatorValues Map of indicator names to their values used in signal generation
 *
 * @since 1.0.0
 */
@Serializable
data class TradingSignal(
    val action: SignalAction,
    val confidence: Double,
    val reason: String,
    @Serializable(with = InstantSerializer::class)
    val timestamp: Instant = Instant.now(),
    val indicatorValues: Map<String, @Contextual Any> = emptyMap()
) {
    init {
        require(confidence >= 0.0 && confidence <= 1.0) {
            "Confidence must be between 0.0 and 1.0, got: $confidence"
        }
        require(reason.isNotBlank()) {
            "Reason cannot be blank"
        }
    }

    /**
     * Check if this signal represents an actionable trade (BUY or SELL).
     */
    fun isActionable(): Boolean = action == SignalAction.BUY || action == SignalAction.SELL

    /**
     * Check if this signal represents a hold action.
     */
    fun isHold(): Boolean = action == SignalAction.HOLD

    /**
     * Check if this signal represents a close action.
     */
    fun isClose(): Boolean = action == SignalAction.CLOSE

    /**
     * Check if confidence meets the minimum threshold.
     *
     * @param threshold Minimum confidence required (default: 0.5)
     * @return true if confidence >= threshold
     */
    fun meetsConfidenceThreshold(threshold: Double = 0.5): Boolean {
        return confidence >= threshold
    }
}

