"""
Excel to Markdown Converter with Auto-Watch
============================================

This script converts Excel files (.xlsx) to Markdown format and can watch
for changes to automatically reconvert when the source files are modified.

Features:
- Converts all sheets in an Excel workbook
- Preserves table structure in Markdown
- Watches for file changes and auto-converts
- Generates readable Markdown files with proper formatting

Requirements:
- Python 3.8+
- pandas
- openpyxl
- watchdog

Install dependencies:
    pip install pandas openpyxl watchdog

Usage:
    # Convert once:
    python excel_to_markdown_converter.py

    # Watch for changes and auto-convert:
    python excel_to_markdown_converter.py --watch

    # Convert specific file:
    python excel_to_markdown_converter.py --file path/to/file.xlsx
"""

import os
import sys
import time
import argparse
from pathlib import Path
from datetime import datetime
from typing import List, Optional

try:
    import pandas as pd
    from watchdog.observers import Observer
    from watchdog.events import FileSystemEventHandler, FileModifiedEvent
except ImportError as e:
    print(f"Error: Missing required package: {e.name}")
    print("\nPlease install required packages:")
    print("  pip install pandas openpyxl watchdog")
    sys.exit(1)


class ExcelToMarkdownConverter:
    """Converts Excel files to Markdown format."""

    def __init__(self, output_dir: Optional[Path] = None):
        """
        Initialize the converter.
        
        Args:
            output_dir: Directory where Markdown files will be saved.
                       If None, saves in the same directory as the Excel file.
        """
        self.output_dir = output_dir

    def convert_excel_to_markdown(self, excel_path: Path) -> Path:
        """
        Convert an Excel file to Markdown.
        
        Args:
            excel_path: Path to the Excel file
            
        Returns:
            Path to the generated Markdown file
        """
        print(f"\n{'='*70}")
        print(f"Converting: {excel_path.name}")
        print(f"{'='*70}")
        
        if not excel_path.exists():
            raise FileNotFoundError(f"Excel file not found: {excel_path}")
        
        # Determine output path
        if self.output_dir:
            output_path = self.output_dir / f"{excel_path.stem}.md"
        else:
            output_path = excel_path.parent / f"{excel_path.stem}.md"
        
        # Read all sheets from the Excel file
        try:
            excel_file = pd.ExcelFile(excel_path, engine='openpyxl')
            sheet_names = excel_file.sheet_names
            
            # Start building the Markdown content
            markdown_content = self._generate_header(excel_path)
            
            # Convert each sheet
            for sheet_name in sheet_names:
                print(f"  Processing sheet: {sheet_name}")
                
                df = pd.read_excel(excel_file, sheet_name=sheet_name)
                
                # Skip empty sheets
                if df.empty:
                    print(f"    ⚠️  Sheet is empty, skipping")
                    continue
                
                markdown_content += self._convert_sheet_to_markdown(sheet_name, df)
            
            # Write to file
            output_path.write_text(markdown_content, encoding='utf-8')
            
            print(f"\n✅ Successfully converted to: {output_path.name}")
            print(f"   Size: {output_path.stat().st_size:,} bytes")
            
            return output_path
            
        except Exception as e:
            print(f"\n❌ Error converting {excel_path.name}: {str(e)}")
            raise

    def _generate_header(self, excel_path: Path) -> str:
        """Generate Markdown header."""
        return f"""# {excel_path.stem}

**Source File**: `{excel_path.name}`  
**Converted**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**Auto-generated**: This file is automatically generated from the Excel source.  
                    Do not edit manually - changes will be overwritten.

---

"""

    def _convert_sheet_to_markdown(self, sheet_name: str, df: pd.DataFrame) -> str:
        """
        Convert a single sheet to Markdown format.
        
        Args:
            sheet_name: Name of the sheet
            df: DataFrame containing the sheet data
            
        Returns:
            Markdown formatted string
        """
        markdown = f"\n## {sheet_name}\n\n"
        
        # Clean up the dataframe
        # Replace NaN with empty strings
        df = df.fillna('')
        
        # Remove completely empty rows
        df = df[df.astype(str).apply(lambda x: x.str.strip().str.len().sum(), axis=1) > 0]
        
        if df.empty:
            markdown += "*No data in this sheet*\n\n"
            return markdown
        
        # Check if this looks like a key-value sheet (2 columns, first column is labels)
        if len(df.columns) == 2 and not df.iloc[:, 0].duplicated().any():
            # Format as key-value pairs
            markdown += self._format_as_key_value(df)
        else:
            # Format as table
            markdown += self._format_as_table(df)
        
        markdown += "\n---\n"
        return markdown

    def _format_as_key_value(self, df: pd.DataFrame) -> str:
        """Format DataFrame as key-value pairs."""
        markdown = ""
        for _, row in df.iterrows():
            key = str(row.iloc[0]).strip()
            value = str(row.iloc[1]).strip()
            if key:  # Only add if key is not empty
                markdown += f"**{key}**: {value}\n\n"
        return markdown

    def _format_as_table(self, df: pd.DataFrame) -> str:
        """Format DataFrame as Markdown table."""
        # Convert to markdown table
        # Handle unnamed columns
        columns = []
        for i, col in enumerate(df.columns):
            if str(col).startswith('Unnamed:') or col == '':
                columns.append(f'Column_{i+1}')
            else:
                columns.append(str(col))
        df.columns = columns
        
        # Convert to markdown
        markdown = df.to_markdown(index=False, tablefmt='github')
        
        if markdown:
            return markdown + "\n"
        else:
            return "*Table conversion failed*\n"


class ExcelFileChangeHandler(FileSystemEventHandler):
    """Handles file system events for Excel files."""

    def __init__(self, converter: ExcelToMarkdownConverter, excel_files: List[Path]):
        """
        Initialize the handler.
        
        Args:
            converter: ExcelToMarkdownConverter instance
            excel_files: List of Excel file paths to monitor
        """
        self.converter = converter
        self.excel_files = {f.resolve(): f for f in excel_files}
        self.last_modified = {}
        
    def on_modified(self, event):
        """Handle file modification events."""
        if event.is_directory:
            return
        
        file_path = Path(event.src_path).resolve()
        
        # Check if this is one of our Excel files
        if file_path not in self.excel_files:
            return
        
        # Ignore temporary Excel files
        if file_path.name.startswith('~$'):
            return
        
        # Debounce: ignore if we just processed this file
        current_time = time.time()
        last_time = self.last_modified.get(file_path, 0)
        if current_time - last_time < 2:  # 2 second debounce
            return
        
        self.last_modified[file_path] = current_time
        
        print(f"\n🔄 Detected change in: {file_path.name}")
        time.sleep(0.5)  # Wait a bit for file to be fully written
        
        try:
            self.converter.convert_excel_to_markdown(file_path)
        except Exception as e:
            print(f"❌ Error during auto-conversion: {e}")


def find_excel_files(directory: Path) -> List[Path]:
    """
    Find all Excel files in a directory.
    
    Args:
        directory: Directory to search
        
    Returns:
        List of Excel file paths
    """
    excel_files = []
    for pattern in ['*.xlsx', '*.xls']:
        excel_files.extend(directory.glob(pattern))
    
    # Filter out temporary files
    excel_files = [f for f in excel_files if not f.name.startswith('~$')]
    
    return sorted(excel_files)


def convert_all_files(source_dir: Path, output_dir: Optional[Path] = None) -> List[Path]:
    """
    Convert all Excel files in a directory.
    
    Args:
        source_dir: Directory containing Excel files
        output_dir: Directory for output Markdown files
        
    Returns:
        List of generated Markdown file paths
    """
    converter = ExcelToMarkdownConverter(output_dir)
    excel_files = find_excel_files(source_dir)
    
    if not excel_files:
        print(f"⚠️  No Excel files found in {source_dir}")
        return []
    
    print(f"\nFound {len(excel_files)} Excel file(s) to convert:")
    for f in excel_files:
        print(f"  - {f.name}")
    
    converted_files = []
    for excel_file in excel_files:
        try:
            md_file = converter.convert_excel_to_markdown(excel_file)
            converted_files.append(md_file)
        except Exception as e:
            print(f"❌ Failed to convert {excel_file.name}: {e}")
    
    return converted_files


def watch_directory(source_dir: Path, output_dir: Optional[Path] = None):
    """
    Watch a directory for Excel file changes and auto-convert.
    
    Args:
        source_dir: Directory to watch
        output_dir: Directory for output Markdown files
    """
    converter = ExcelToMarkdownConverter(output_dir)
    excel_files = find_excel_files(source_dir)
    
    if not excel_files:
        print(f"⚠️  No Excel files found in {source_dir}")
        return
    
    print(f"\n👁️  Watching {len(excel_files)} Excel file(s) for changes:")
    for f in excel_files:
        print(f"  - {f.name}")
    
    event_handler = ExcelFileChangeHandler(converter, excel_files)
    observer = Observer()
    observer.schedule(event_handler, str(source_dir), recursive=False)
    observer.start()
    
    print(f"\n✅ Watching directory: {source_dir}")
    print("   Press Ctrl+C to stop...\n")
    
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\n\n🛑 Stopping file watch...")
        observer.stop()
    
    observer.join()
    print("✅ File watch stopped.")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description='Convert Excel files to Markdown with auto-watch capability',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Convert all Excel files in 02_ReqMgn folder once:
  python excel_to_markdown_converter.py
  
  # Watch for changes and auto-convert:
  python excel_to_markdown_converter.py --watch
  
  # Convert specific file:
  python excel_to_markdown_converter.py --file myfile.xlsx
  
  # Specify custom directories:
  python excel_to_markdown_converter.py --source ../02_ReqMgn --output ./output
        """
    )
    
    parser.add_argument(
        '--source',
        type=Path,
        default=None,
        help='Source directory containing Excel files (default: ../../02_ReqMgn)'
    )
    
    parser.add_argument(
        '--output',
        type=Path,
        default=None,
        help='Output directory for Markdown files (default: same as source)'
    )
    
    parser.add_argument(
        '--file',
        type=Path,
        help='Convert a specific Excel file'
    )
    
    parser.add_argument(
        '--watch',
        action='store_true',
        help='Watch for file changes and auto-convert'
    )
    
    args = parser.parse_args()
    
    # Determine source directory
    if args.file:
        # Convert single file
        converter = ExcelToMarkdownConverter(args.output)
        try:
            converter.convert_excel_to_markdown(args.file)
            print("\n✅ Conversion complete!")
        except Exception as e:
            print(f"\n❌ Conversion failed: {e}")
            sys.exit(1)
        return
    
    # Determine source directory
    if args.source:
        source_dir = args.source
    else:
        # Default: relative to this script (Cursor folder -> 02_ReqMgn)
        # Script is at: .../Application_OnPremises/Cursor/
        # We need: .../02_ReqMgn
        # Path: Cursor -> Application_OnPremises -> 03_Development -> FMPS_AutoTraderApplication -> 02_ReqMgn
        script_dir = Path(__file__).parent
        source_dir = script_dir.parent.parent.parent / '02_ReqMgn'
    
    source_dir = source_dir.resolve()
    
    if not source_dir.exists():
        print(f"❌ Error: Source directory does not exist: {source_dir}")
        sys.exit(1)
    
    print(f"Source directory: {source_dir}")
    if args.output:
        print(f"Output directory: {args.output.resolve()}")
        args.output.mkdir(parents=True, exist_ok=True)
    
    # Convert all files first
    print("\n" + "="*70)
    print("INITIAL CONVERSION")
    print("="*70)
    converted_files = convert_all_files(source_dir, args.output)
    
    if converted_files:
        print(f"\n✅ Successfully converted {len(converted_files)} file(s)")
    
    # Watch for changes if requested
    if args.watch:
        print("\n" + "="*70)
        print("STARTING FILE WATCH")
        print("="*70)
        watch_directory(source_dir, args.output)
    else:
        print("\n✅ All conversions complete!")
        print("   Tip: Use --watch flag to automatically convert when files change")


if __name__ == '__main__':
    main()

